import type { Metadata } from "next";
import { Source_Code_Pro } from "next/font/google";
import "./globals.css";

const sourceCodeProp = Source_Code_Pro({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  parallel,
}: {
  children: React.ReactNode;
  parallel: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={sourceCodeProp.className}>
        <fieldset>
          <legend>PARALLEL</legend>
          <div>{parallel}</div>
        </fieldset>
        <fieldset>
          <legend>MAIN</legend>
          <main>{children}</main>
        </fieldset>
      </body>
    </html>
  );
}
